# Generated by Django 4.2.7 on 2023-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='detailer',
            name='address',
        ),
        migrations.AddField(
            model_name='checker',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailer',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
