# Generated by Django 5.0.1 on 2024-01-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='MainProject',
        ),
    ]
