# Generated by Django 4.2.7 on 2023-12-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_status', models.CharField(choices=[('start', 'Start'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=200)),
                ('percentage', models.IntegerField(default=0)),
                ('daily_description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.project')),
            ],
        ),
    ]
