# Generated by Django 4.2.7 on 2023-11-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_remove_checker_address_remove_detailer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('detailer', 'Detailer'), ('admin', 'Admin'), ('checker', 'Checker')], max_length=50),
        ),
    ]
