# Generated by Django 4.2.3 on 2023-12-13 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_remove_client_email_remove_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
