# Generated by Django 5.0.1 on 2024-01-03 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0002_projectstatus_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='first_check_complete',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='second_check_complete',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
