# Generated by Django 4.2.7 on 2023-12-22 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_project_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='submission_date',
        ),
        migrations.CreateModel(
            name='SubmissionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.project')),
            ],
        ),
    ]
