# Generated by Django 5.0.1 on 2024-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_project_comments_project_first_check_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_check_complete',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_check_complete',
            field=models.DateField(default=None),
        ),
    ]
