# Generated by Django 4.2.7 on 2023-11-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('detailer', 'Detailer'), ('management', 'Management'), ('checker', 'Checker')], max_length=50),
        ),
    ]
