# Generated by Django 5.0.1 on 2024-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_alter_project_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_submission',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_check_complete',
            field=models.DateField(default='None'),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_check_complete',
            field=models.DateField(default='None'),
        ),
    ]
