# Generated by Django 4.2.7 on 2023-12-22 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_remove_project_submission_date_submissionprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubmissionProgram',
        ),
    ]
