# Generated by Django 4.2.7 on 2023-11-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
