# Generated by Django 4.2.7 on 2023-12-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0005_project_submission_date_delete_submissionprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assumed_no_of_sheet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='assumed_wt',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
