# Generated by Django 4.2.7 on 2023-11-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0005_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
