# Generated by Django 5.0.1 on 2024-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0006_alter_project_actual_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_submission',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_check_complete',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='second_check_complete',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
