# Generated by Django 5.0.1 on 2024-01-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0007_alter_project_actual_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_submission',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
