# Generated by Django 5.0.1 on 2024-01-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0008_alter_project_actual_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
    ]
