# Generated by Django 5.0.1 on 2024-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0009_delete_monthlyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_check_complete',
            field=models.DateField(blank=True, default='00/00/0000', null=True),
        ),
    ]
