# Generated by Django 5.0.1 on 2024-01-05 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0012_alter_project_first_check_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='first_check_complete',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='second_check_complete',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
