# Generated by Django 5.0.1 on 2024-01-05 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0013_alter_project_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_submission',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
