# Generated by Django 5.0.1 on 2024-01-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0015_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
